export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const INIT_INGREDIENTS = "INIT_INGREDIENTS";
export const FAIL_INIT_INGREDIENTS = "FAIL_INIT_INGREDIENTS";

export const SUCCESS_ORDER = "SUCCESS_ORDER";
export const FAIL_ORDER = "FAIL_ORDER";
export const STORING_ORDER = "STORING_ORDER";
export const REDIRECT_ORDER = "REDIRECT_ORDER";

export const GET_ORDERS_START = "GET_ORDERS_START";
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";
export const GET_ORDERS_FAIL = "GET_ORDERS_FAIL";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
